name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Make all (go generate, build + test)
      run: make all

    - name: Update AS Data
      run: ./updateASData.sh

    - name: Smoke Test
      run: sudo timeout --preserve-status --signal=INT 10s ./bin/amd64/socket-connect-bpf -a

    - name: Create Build Artifact
      run: |
        mkdir -p bin/amd64/as
        mkdir -p bin/arm64/as
        cp ./README.md bin/amd64/
        cp ./README.md bin/arm64/
        cp as/ip2asn-v4-u32.tsv bin/amd64/as/
        cp as/ip2asn-v4-u32.tsv bin/arm64/as/
        mkdir artifacts
        tar czf artifacts/socket-connect-bpf-linux-amd64.tar.gz --directory=bin/amd64/ .
        tar czf artifacts/socket-connect-bpf-linux-arm64.tar.gz --directory=bin/arm64/ .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: socket-connect-bpf
        path: artifacts
