name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate BPF Sources
      run: go generate

    - name: Execute Tests
      run: go test ./...
      
    - name: Build
      run: go build -v .

    - name: Update AS Data
      run: ./updateASData.sh

    #- name: Smoke Test
    #  run: sudo timeout --preserve-status --signal=INT 10s ./socket-connect-bpf -a

    - name: Create Build Artifact
      run: |
        mkdir -p dist/as
        mv ./socket-connect-bpf dist/
        mv ./README.md dist/
        mv as/ip2asn-v4-u32.tsv dist/as/
        mkdir artifacts
        tar czf artifacts/socket-connect-bpf-linux-x64.tar.gz --directory=dist/ .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: socket-connect-bpf
        path: artifacts
