name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Install Upstream BCC Tools
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
        echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
        sudo apt update
        sudo apt install bcc-tools libbcc-examples linux-headers-$(uname -r)

    - name: Generate BPF Sources
      run: go generate

    - name: Execute Tests
      run: go test ./...
      
    - name: Build
      run: go build -v .

    - name: Update AS Data
      run: ./updateASData.sh

    - name: Smoke Test
      run: sudo timeout --preserve-status --signal=INT 10s ./socket-connect-bpf -a

    - name: Create Build Artifact
      run: |
        mkdir -p dist/as
        mv ./socket-connect-bpf dist/
        mv ./README.md dist/
        mv as/ip2asn-v4-u32.tsv dist/as/
        mkdir artifacts
        tar czf artifacts/socket-connect-bpf.tar.gz --directory=dist/ .

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: socket-connect-bpf
        path: artifacts
